### ISSUE TITLE
debug mode + flash false = error

### ISSUE THREAD

**Issue by RRShieldsCutler** [knights-lab/shi7#42] opened 2017-04-14 23:03 UTC
Error when running debug mode with `--flash False`. Looks like it is searching for trimmer files (which presumably don't exist with flash == False). Doesn't kill the process or affect the file output, that I can tell.

```
Traceback (most recent call last):
  File "/export/scratch/robin/miniconda3/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/project/flatiron2/data/public_shotgun/qin2014/adapator_test/truseq2/temp/trimmer/HD.10.fastq' -> '/project/fl
atiron2/data/public_shotgun/qin2014/adapator_test/truseq2/HD.10.fastq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/flatiron2/sop/shi7.py", line 383, in <module>
    main()
  File "/project/flatiron2/sop/shi7.py", line 376, in main
    shutil.move(file, args.output)
  File "/export/scratch/robin/miniconda3/lib/python3.5/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/export/scratch/robin/miniconda3/lib/python3.5/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/export/scratch/robin/miniconda3/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/project/flatiron2/data/public_shotgun/qin2014/adapator_test/truseq2/temp/trimmer/HD.10.fastq'
```

**Comment by GabeAl** [comment] 2017-04-14 23:52
Why are you assuming trimming files don't exist without flash? Maybe it's a
quirk in the wording. When you want to run a paired end pipeline without
flashing, you'd still like to do the other steps -- parse, trim adaptors,
post-trim, convert, combine right?

What happens if you also add --adaptor none (or omit the adaptor part
entirely)?

Or is it failing on the trim step that usually comes after the flash?

Cheerio!

**Comment by RRShieldsCutler** [comment] 2017-04-15 00:32
That's why I said "presumably"... because I'm not 100% certain what exactly is happening ;)
But, the `temp/trimmer/` directory is empty.

Trying a couple other things. Will update.

**Comment by RRShieldsCutler** [comment] 2017-04-15 03:19
Mmmmkay. I did seven different combinations. Two findings:
1. Combination of `-flash False` and `-s True` produces the error above (debug and adaptor don't matter).
2. Passing in "None" (with or without quotes) results in the following error:
```
usage: shi7 v0.91 -i <input> -o <output> ...
shi7.py: error: argument --adaptor: invalid choice: 'None' (choose from None, 'Nextera', 'TruSeq3', 'TruSeq2', 'TruSeq3-2')
```

**Comment by GabeAl** [comment] 2017-04-15 04:57
Gotcha. Yup this is definitely the "second" trimming stage (independent of the adaptor trimming). My guess is shi7.py (through shi7_trimmer) is expecting the flash step to transform the file name in a generic enough way that the downstream steps (trimmer, convert/combine) are OK with it. I think the solution is for the program to detect it's working with a stripped R1 read where "R1" may have been explicitly added after it was stripped. What are the file names in the 'axe' folder if you enable adaptor trimming? 

Also, probably no hope here but does the log/terminal list anything about the trimmer itself failing to find its input (or what input file name it was looking for)? I don't think shi7_trimmer actually got anything to work on if the trimmer directory is empty, which supports the theory above.

I'm assigning Kaiwei to this one -- hopefully this is enough info to reproduce (Kaiwei, I think it's sufficient to change the test fastq names to the ones Robin is using and use his commandline). 

Thanks again for the report!

PS: To the adaptor point -- okay, seems the only way to specify "None" is to omit the argument (maybe that's why it's not in quotes like the other options seem to be).

**Comment by GabeAl** [comment] 2017-04-15 04:59
@RRShieldsCutler Could you provide the filenames and the commandline used to reproduce the issue? 
@kaiweiang Let us know if you need any more info to reproduce the problem. I think changing the test fastq filenames will be enough, but I could be wrong.

**Comment by RRShieldsCutler** [comment] 2017-04-15 12:50
@kaiweiang Try it with these filenames:
```
HC-10_Run1.1.fastq
HC-10_Run1.2.fastq
```
This command should reproduce the error:
`shi7.py --adaptor TruSeq2 --flash false --convert_fasta False --combine_fasta False -filter_l 50 -i . -o test5 -s True`

**Comment by kaiweiang** [comment] 2017-04-18 21:01
@RRShieldsCutler Hi, did you try to run without `-s True`?

**Comment by RRShieldsCutler** [comment] 2017-04-18 21:06
@kaiweiang Here are the permutations I tried, and whether they worked ("SUCCESS") or resulted in error ("ERROR"):
```
$ shi7.py --flash False --convert_fasta False --combine_fasta False -filter_l 50 -i . --debug -s True -o test1
ERROR

$ shi7.py --flash False --convert_fasta False --combine_fasta False -filter_l 50 -i . --debug -o test2
SUCCESS

$ shi7.py --convert_fasta False --combine_fasta False -filter_l 50 -i . --debug -o test3 -s True
SUCCESS

$ shi7.py --adaptor TruSeq2 --convert_fasta False --combine_fasta False -filter_l 50 -i . --debug -o test4 -s True
SUCCESS

$ shi7.py --adaptor TruSeq2 --flash false --convert_fasta False --combine_fasta False -filter_l 50 -i . -o test5 -s True
ERROR
```
I did run a couple others with `--adaptor None` which raised a different error, as @GabeAl addressed above.

**Comment by kaiweiang** [comment] 2017-04-19 05:42
@GabeAl 
I tried running the same combinations of parameters with our default testfastqs and got the exact same issue too. It seems the `--strip_underscore` feature is buggy. I can't rmb who wrote this, was it you or Ben? 

Here's an issue arise when running `-s true` and `--flash false`:
The original input fastqs are
`GA01.S001.L001.R1.001.fastq`
`GA01.S001.L001.R2.001.fastq`
`GA01.S002.L001.R1.001.fastq`
`GA01.S002.L001.R1.001.fastq`

After being stripped and skipping the flash, the fastq names are 
`GA01R1.fastq`
`GA01R2.fastq`
`GA01R1.fastq`
`GA01R2.fastq`

As you can see, the filenames are **not unique** and this is the cause of the errors.

**Comment by GabeAl** [comment] 2017-04-19 13:29
I think I added it, but I'm not sure where it's messing up.

About the unique file names, yes, that is one issue. But just trying on a
single correctly and uniquely named pair shows there's more going on:

@kaiweiang <https://github.com/kaiweiang> Try it with these filenames:

HD-10_Run1.1.fastq
HD-10_Run1.2.fastq

**Comment by bhillmann** [comment] 2017-04-19 14:45
This code was designed this way, but I wrote it up.

In order to avoid dealing with this issue, and other issues similar to this in the future, can we force the user to supply a mapping file for samples?

**Comment by kaiweiang** [comment] 2017-04-19 17:13
@GabeAl 
Yeah, given the input fastqs 
`HD-10_Run1.1.fastq`
`HD-10_Run1.2.fastq`
Two `HD.10.fastq` are created since the first strip_underscore which occurred in axe_adaptor stage. The `shi7_trimmer` somehow doesn't yield the expected output whenever there are two or more same filenames.

**Comment by GabeAl** [comment] 2017-04-19 22:36
Interesting. I think we should add an R1/R2 if the filenames get messed up,
and then rip them off later if necessary (flash should do this
automatically when it creates an extendedFrags output).

Would you be able to figure out where it's going wrong? Any way you could
come up with a nice fix? :)

**Comment by kaiweiang** [comment] 2017-04-20 19:38
I'll see what I can do 👍

**Comment by kaiweiang** [comment] 2017-04-21 23:46
@GabeAl @bhillmann 
The current implementation of `--strip_underscore` (ofc only happen when --strip_underscore is true) with or without flash will cause shi7 to behave incorrectly as soon as at the axe_adaptor stage and hence all the subsequent stages will be affected too. 

In conclusion, the current implementation of `--strip_underscore` has two problems

1st case:
Given filenames
`HD-10_Run1.1.fastq`
`HD-10_Run1.2.fastq`
Although with `--flash True` and `-s True` did not yield error and output normally, the output is actually incorrect! 

2nd case:
`GA01_S001_L001_R1_001.fastq`
`GA01_S002_L001_R1_001.fastq`
will also yield two `GA01R1.fastq` when `-s True` and hence the output will be incorrectly too.

So do you think we should force users to add 'R1' and 'R2' in the filenames? 
I think the second problem can be solved by splitting BOTH dot and underscore (the current implementation only splits underscore). However, I can't guarantee this will work for all types of filenames.

**Comment by GabeAl** [comment] 2017-04-22 03:04
Users should not have to be forced to do anything. The purpose of this
feature is for convenience so they don't have to rename their files. This
is important when there are hundreds of files and renaming them is
burdensome.

The software should be smart enough to do this by itself. In both cases you
mention, shi7 should add the R1 and R2 to the first and second file (
*replacing* everything after the underscore with R1 and R2 for the correct
reads) and have the pipeline proceed correctly.

How does that sound? :)

Cheers,
Gabe

**Comment by GabeAl** [comment] 2017-08-24 01:21
As @kaiweiang mentioned, this problem was actually related to other factors. The strip_underscores command as well as (at the time) a faulty R1/R2 decoupler contributed to thinking this was the actual bug, when it was not.

**Closed as completed by GabeAl** 2017-08-24 01:21 UTC
