### ISSUE TITLE
Shi7 removes R1 or R2 while keeping the other with --combine_fasta False

### ISSUE THREAD

**Issue by danknights** [knights-lab/shi7#52] opened 2017-09-09 19:51 UTC
E.g. a read in R1 fastq might be removed due to QC, but the reverse read in R2 gets retained, or vice versa. This leads to mismatched R1 and R2 files which breaks later processing.

Solution: When dropping an R1 read the corresponding R2 must also be dropped.

**Comment by GabeAl** [comment] 2017-09-11 18:25
Hi! Few clarifications needed:
1. What's your commandline? 
2. What do you mean by "later processing"?
3. Could you attach the shi7.log file?

We've seen lots of lingering R1 and R2 mismatch issues due to bugs in parsing filenames causing bad interpretation of pairs at the outset. But I haven't yet seen a case where it is caused by discarding one read or other other in a pair during QC (we tried to set up all the intermediate programs not to do this either, and we only use the files where both are kept [trimmomatic], discard pairs rather than singles if there's bad quality [shi7_trim], grab only the stitched cases where the two ends stitch [flash], etc. 

If the program is run in SE mode, though, or with flash=false, it becomes unaware of whether there's an R1 or R2 in the bunch. 

If by "later processing" you mean downstream stuff after QC is done (paired aligning, etc), and you're running in non-SE mode with flash=false, you would currently have to signal to the downstream program that you're dealing with unmatched pairs. Some tools don't support this case either, and we can try to fix if this is what you meant!

**Comment by GabeAl** [comment] 2017-09-19 19:35
@danknights ping!

**Comment by GabeAl** [comment] 2017-11-20 23:50
@danknights still happening with latest version?

**Comment by GabeAl** [comment] 2018-05-30 17:15
Should be fixed in latest version!

**Closed as completed by GabeAl** 2018-05-30 17:15 UTC
Labels: bug, urgent

**Comment by matthpich** [comment] 2018-06-25 16:33
Hi,
It could be useful to keep the unpaired-after-QC reads as well.
They can be a significant amount of them and they can be used by assemblers, such as Spades, and other tools.
